# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daemon_sysmon.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61\x65mon_sysmon.proto\"6\n\x12SystemStatsRequest\x12\x10\n\x08interval\x18\x01 \x01(\x05\x12\x0e\n\x06window\x18\x02 \x01(\x05\"\x91\x01\n\x0e\x46ilesystemInfo\x12\x12\n\nfilesystem\x18\x01 \x01(\t\x12\x0e\n\x06inodes\x18\x02 \x01(\x03\x12\r\n\x05iused\x18\x03 \x01(\x03\x12\x1f\n\x17iuse_calculated_percent\x18\x04 \x01(\t\x12\x0f\n\x07used_mb\x18\x05 \x01(\t\x12\x1a\n\x12space_used_percent\x18\x06 \x01(\t\"\x89\x01\n\x07\x43puInfo\x12\x11\n\tuser_mode\x18\x01 \x01(\t\x12\x13\n\x0bsystem_mode\x18\x02 \x01(\t\x12\x11\n\tidle_mode\x18\x03 \x01(\t\x12\x14\n\x0cload_avg_min\x18\x04 \x01(\t\x12\x15\n\rload_avg_5min\x18\x05 \x01(\t\x12\x16\n\x0eload_avg_15min\x18\x06 \x01(\t\"Y\n\x0b\x44\x65viceStats\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x0b\n\x03tps\x18\x02 \x01(\t\x12\x15\n\rkb_read_per_s\x18\x03 \x01(\t\x12\x16\n\x0ekb_write_per_s\x18\x04 \x01(\t\"Y\n\x0bNetworkInfo\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x10\n\x08protocol\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\t\"\xb0\x01\n\x13TcpConnectionStates\x12\r\n\x05\x65stab\x18\x01 \x01(\x05\x12\x10\n\x08\x66in_wait\x18\x02 \x01(\x05\x12\x0f\n\x07syn_rcv\x18\x03 \x01(\x05\x12\x11\n\ttime_wait\x18\x04 \x01(\x05\x12\x12\n\nclose_wait\x18\x05 \x01(\x05\x12\x10\n\x08last_ack\x18\x06 \x01(\x05\x12\x0e\n\x06listen\x18\x07 \x01(\x05\x12\r\n\x05\x63lose\x18\x08 \x01(\x05\x12\x0f\n\x07unknown\x18\t \x01(\x05\"\xbc\x01\n\x0bSystemStats\x12$\n\x0b\x66ilesystems\x18\x01 \x03(\x0b\x32\x0f.FilesystemInfo\x12\x15\n\x03\x63pu\x18\x02 \x01(\x0b\x32\x08.CpuInfo\x12\x1d\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32\x0c.DeviceStats\x12\'\n\x11listening_sockets\x18\x04 \x03(\x0b\x32\x0c.NetworkInfo\x12(\n\ntcp_states\x18\x05 \x01(\x0b\x32\x14.TcpConnectionStates2J\n\x11SystemInfoService\x12\x35\n\x0eGetSystemStats\x12\x13.SystemStatsRequest\x1a\x0c.SystemStats0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daemon_sysmon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMSTATSREQUEST']._serialized_start=23
  _globals['_SYSTEMSTATSREQUEST']._serialized_end=77
  _globals['_FILESYSTEMINFO']._serialized_start=80
  _globals['_FILESYSTEMINFO']._serialized_end=225
  _globals['_CPUINFO']._serialized_start=228
  _globals['_CPUINFO']._serialized_end=365
  _globals['_DEVICESTATS']._serialized_start=367
  _globals['_DEVICESTATS']._serialized_end=456
  _globals['_NETWORKINFO']._serialized_start=458
  _globals['_NETWORKINFO']._serialized_end=547
  _globals['_TCPCONNECTIONSTATES']._serialized_start=550
  _globals['_TCPCONNECTIONSTATES']._serialized_end=726
  _globals['_SYSTEMSTATS']._serialized_start=729
  _globals['_SYSTEMSTATS']._serialized_end=917
  _globals['_SYSTEMINFOSERVICE']._serialized_start=919
  _globals['_SYSTEMINFOSERVICE']._serialized_end=993
# @@protoc_insertion_point(module_scope)
